---
title: "Raster Pre-Processing"
output: html_document
date: "2023-12-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
```

## R Markdown

```{r}
library(osmdata)
library(sf)
library(ggplot2)
library(raster)
library(dplyr)
library(readr)
library(terra)
library(spdep)


# Capture the start time
start_time <- Sys.time()
```

## Setting Parameters
```{r}
coordinate_system <- 4326
# Target resolution in m
resolution <- 30
# Conversion to degrees
resolution <- (resolution/30)/3600

```

```{r, echo=FALSE}
# Read the GeoJSON file
cropbox <- st_read("https://raw.githubusercontent.com/HotspotStoplight/HotspotStoplight/main/CropBoxes/CR_Crop4.geojson")
cropbox <- st_read("https://raw.githubusercontent.com/HotspotStoplight/HotspotStoplight/main/CropBoxes/CR_Crop5.geojson")
cropbox <- st_read("https://raw.githubusercontent.com/HotspotStoplight/HotspotStoplight/main/CropBoxes/CR_Crop5b.geojson")
cropbox <- st_read("https://raw.githubusercontent.com/HotspotStoplight/HotspotStoplight/main/CropBoxes/CR_Crop6.geojson")

# Read the rasters
dist_road = raster('https://raw.githubusercontent.com/HotspotStoplight/HotspotStoplight/main/UrbanExpansion/data/roads_proximity.tif')
pop2020 = raster('/Users/oliveratwood/Documents/GitHub/HotspotStoplight/UrbanExpansion/data/Pop_2020_Crop4.tif')
BII = raster('/Users/oliveratwood/Documents/GitHub/HotspotStoplight/UrbanExpansion/data/BiodiversityIntactness_2020.tif')
LC_Vul_Clark = raster('/Users/oliveratwood/Documents/GitHub/HotspotStoplight/UrbanExpansion/data/Land_Cover_Vulnerability.tif')
```

```{r, echo=FALSE}
# Project the rasters
pop2020 <- projectRaster(pop2020, crs = coordinate_system, method = "bilinear")
BII <- projectRaster(BII, crs = coordinate_system, method = "bilinear")
LC_Vul_Clark <- projectRaster(LC_Vul_Clark, crs = coordinate_system, method = "bilinear")

```

```{r}
# Resample each raster to match the resolution of prox_road
pop2020 <- resample(pop2020, dist_road, method = "bilinear")
BII <- resample(BII, dist_road, method = "bilinear")
LC_Vul_Clark <- resample(LC_Vul_Clark, dist_road, method = "bilinear")
```

```{r, echo=FALSE}
# Clip the rasters with the polygon
pop2020 <- crop(pop2020, cropbox)
BII <- crop(BII, cropbox)
LC_Vul_Clark <- crop(LC_Vul_Clark, cropbox)
```

```{r}
plot(pop2020)
plot(BII)
plot(LC_Vul_Clark)
```

```{r, echo=FALSE}
# # Check for Uniformity of raster data
# # Check Resolution
# res(pop2020)
# 
# # Check Extents
# extent(pop2020)
# 
# # Check Coordinate Systems
# crs(pop2020)

```

```{r}
# Save the rasters to the directory
setwd("/Users/oliveratwood/Documents/GitHub/HotspotStoplight/clustering/data")


writeRaster(pop2020, filename = "Pop_2020.tif", format = "GTiff", overwrite=TRUE)
writeRaster(BII, filename = "BII.tif", format = "GTiff", overwrite=TRUE)
writeRaster(LC_Vul_Clark, filename = "LC_Vul_Clark.tif", format = "GTiff", overwrite=TRUE)
```

```{r}
BII = raster('/Users/oliveratwood/Documents/GitHub/HotspotStoplight/clustering/data/BII.tif')
plot(BII)
```


```{r timer_end}
# Capture the end time
end_time <- Sys.time()

# Calculate and print the runtime
runtime <- end_time - start_time
print(paste("Total runtime:", runtime))
```

