---
title: "OSM Data Wrangling"
output: html_document
date: "2023-09-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
```

## R Markdown

```{r}
library(osmdata)
library(sf)
library(ggplot2)
library(raster)
library(dplyr)

# Capture the start time
start_time <- Sys.time()
```

## Setting Parameters
```{r}
# Coordinates
# coords <- c(159, -10.40, 161.5, -8.75)
coords <- c(159.87837324022547, -9.506012864979633, 160.11732587694422, -9.365122938868943)
coordinate_system <- 32756
resolution <- 30

```

```{r Extablish bbox, echo=FALSE}
# Create a rectangle (polygon) from the coordinates
rectangle <- st_polygon(list(matrix(c(coords[1], coords[2],
                                     coords[1], coords[4],
                                     coords[3], coords[4],
                                     coords[3], coords[2],
                                     coords[1], coords[2]), 
                                     ncol=2, byrow=TRUE)))

# Create an sf object and set its CRS to EPSG:4326 (WGS 84)
rectangle_sf <- st_sf(geometry = st_sfc(rectangle, crs = 4326))

# Get the bounding box
bbox <- st_bbox(rectangle_sf)

# Reproject the rectangle to EPSG:32756 (UTM Zone 56S)
rectangle_sf_utm <- st_transform(rectangle_sf, coordinate_system)

# Get the bounding box
bbox_utm <- st_bbox(rectangle_sf_utm)

```

## Download OSM Data
```{r Download OSM Data, echo=FALSE}
# Query Roads Data from OSM
roads_data_1 <- opq(bbox) %>%
  add_osm_feature(key = "highway", value = "secondary") %>%
  osmdata_sf()

roads_data_2 <- opq(bbox) %>%
  add_osm_feature(key = "highway", value = "tertiary") %>%
  osmdata_sf()

roads_data_3 <- opq(bbox) %>%
  add_osm_feature(key = "highway", value = "residential") %>%
  osmdata_sf()
```

```{r pre-process, echo=FALSE}
# Convert the roads data to a simple feature object
roads_1 <- roads_data_1$osm_lines
roads_utm_1 <- st_transform(roads_1, coordinate_system)
roads_utm_1 <- st_simplify(roads_utm_1, dTolerance = resolution)

roads_2 <- roads_data_2$osm_lines
roads_utm_2 <- st_transform(roads_2, coordinate_system)
roads_utm_2 <- st_simplify(roads_utm_2, dTolerance = resolution)

roads_3 <- roads_data_3$osm_lines
roads_utm_3 <- st_transform(roads_3, coordinate_system)
roads_utm_3 <- st_simplify(roads_utm_3, dTolerance = resolution)

# Combine roads
all_roads <- bind_rows(roads_utm_1, roads_utm_2, roads_utm_3)

# Isolate highways
highway <- st_simplify(roads_utm_1, dTolerance = resolution)


# Plot using ggplot2
ggplot(data = all_roads) +
  geom_sf() +
  theme_minimal() +
  labs(title = "Imported Roads")


```

## Rasterize Roads Data
```{r RASTERIZE, fig.width=max}
bbox_utm_extent <- extent(c(bbox_utm["xmin"], bbox_utm["xmax"], bbox_utm["ymin"], bbox_utm["ymax"]))

# Empty raster
r <- raster(bbox_utm_extent, res = resolution, crs = st_crs(coordinate_system))

### ALL ROADS 
# Rasterize road count
roads_raster_utm <- rasterize(all_roads, r, field = 1, fun = "count")
# Clone the roads_raster_utm to create binary_roads_raster
binary_roads_raster <- roads_raster_utm
# Replace all non-zero values with 1
binary_roads_raster[binary_roads_raster > 0] <- 1
# Replace all zero values with NA
binary_roads_raster[binary_roads_raster == 0] <- NA
# Compute road proximity
road_proximity <- distance(binary_roads_raster)

### HIGHWAY
highway_raster_utm <- rasterize(highway, r, field = 1, fun = "count")
binary_highway_raster <- highway_raster_utm
binary_highway_raster[binary_highway_raster > 0] <- 1
binary_highway_raster[binary_highway_raster == 0] <- NA
highway_proximity <- distance(binary_highway_raster)

# Plot the rasters
plot(roads_raster_utm, main = "Roads Rasterized (Count)")
plot(binary_roads_raster, main = "Roads Rasterized (Binary)")
plot(road_proximity, main = "Proximity to Roads")
plot(highway_proximity, main = "Proximity to highways")

# write rasters
writeRaster(binary_roads_raster, filename = "/Users/oliveratwood/Documents/GitHub/HotspotStoplight/R-scripts/data/roads_binary.tif", format = "GTiff", overwrite = TRUE)
writeRaster(road_proximity, filename = "/Users/oliveratwood/Documents/GitHub/HotspotStoplight/R-scripts/data/roads_proximity.tif", format = "GTiff", overwrite = TRUE)
writeRaster(binary_highway_raster, filename = "/Users/oliveratwood/Documents/GitHub/HotspotStoplight/R-scripts/data/highway_binary.tif", format = "GTiff", overwrite = TRUE)
writeRaster(highway_proximity, filename = "/Users/oliveratwood/Documents/GitHub/HotspotStoplight/R-scripts/data/highway_proximity.tif", format = "GTiff", overwrite = TRUE)

```

```{r timer_end}
# Capture the end time
end_time <- Sys.time()

# Calculate and print the runtime
runtime <- end_time - start_time
print(paste("Total runtime:", runtime))
```

